sudo: false
language: go
go:
    - "tip"
install:
  - go get github.com/gorilla/mux
  - go get github.com/gorilla/context
  - go get github.com/dgrijalva/jwt-go
services:
    - docker
before_install:
    - sleep 15
    - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
after_success:
    - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o jwtea
    - sleep 5
    - docker build -t awaseem/jwtea:$TRAVIS_BRANCH-$TRAVIS_GO_VERSION .
    - sleep 5
    - docker push awaseem/jwtea:$TRAVIS_BRANCH-$TRAVIS_GO_VERSION
    - docker logout